version: "3.8"

services:
    # discoveryserver:
    #     build:
    #         context: .
    #         dockerfile: discoverServer/Dockerfile
    #     ports:
    #         - "8761:8761"
    #     networks:
    #         - microservice-networks
    # postgres:
    #     image: postgres
    #     restart: always
    #     ports:
    #         - "5432:5432"
    #     environment:
    #         POSTGRES_DB: bookservice
    #         POSTGRES_USER: postgres
    #         POSTGRES_PASSWORD: postgres
    #     networks:
    #         - microservice-networks
    bookservice:
        build:
            context: .
            dockerfile: bookService/Dockerfile
        ports:
            - "9001:9001"
        networks:
            - microservice-networks
        # depends_on:
        #     - discoveryserver
        #     - postgres
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bookservice
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: postgres
networks:
    microservice-networks:
        driver: bridge