server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discover:
        locator:
          enabled: true
      routes:
        - id: bookservice
          uri: lb://bookservice
          predicates:
            - Path=/api/v1/book/**

eureka:
  instance:
    hostname: discoveryserver
  client:
    service-url:
      defaultZone: http://discoveryserver:8761/eureka
      register-with-eureka: true
      fetch-registry: true